### ISSUE TITLE
n1punp - FeeGrowthInside calculation doesn't allow overflowing/underflowing

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-real-wagmi-judging#1]
n1punp

high

# FeeGrowthInside calculation doesn't allow overflowing/underflowing

## Summary
When calculating `feeGrowthInside` , the calculation doesn't allow overflowing/underflowing. 

## Vulnerability Detail
When calculating `feeGrowthInside` , the calculation doesn't allow overflowing/underflowing. See more details in https://github.com/Uniswap/v3-core/issues/573 

## Impact
Calculation can revert in some situations, causing the transactions to revert, including `deposit` function.

## Code Snippet
https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Multipool.sol#L668-L690

## Tool used

Manual Review

## Recommendation
- Use `unchecked` in the calculation to allow under/overflow.

Duplicate of #46

**Comment by n1punp** [comment]
Escalate

Medium severity is okay, per @ctf-sec . But this should be a valid issue.

**Comment by sherlock-admin** [comment]
> Escalate
> 
> Medium severity is okay, per @ctf-sec . But this should be a valid issue.

    You've deleted an escalation for this issue.

**Comment by n1punp** [comment]
Escalate 

Same as #46

**Comment by sherlock-admin** [comment]
> Escalate 
> 
> Same as #46 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
Agree with escalation, this is a duplicate of #46

**Comment by hrishibhat** [comment]
Result:
Medium
Duplicate of #46

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [n1punp](https://github.com/sherlock-audit/2023-06-real-wagmi-judging/issues/1/#issuecomment-1632598572): accepted

**Comment by fann95** [comment]
fixed: https://github.com/RealWagmi/concentrator/blob/9036fe43b0de2694a0c5e18cfe821d40ce17a9b8/contracts/Multipool.sol#L675

**Comment by 0xffff11** [comment]
Fixed by adding unchecked several times to all the calculations to allow under/overflowing as it is intended for uniswap libs. Also, instead of using that many unchecked, sponsor could use one, but scope all the code. Regardless, it is also fixed this way.
