### ISSUE TITLE
Phantasmagoria - Missing transaction expiration check result in reward tokens selling at a lower price

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-real-wagmi-judging#102]
Phantasmagoria

medium

# Missing transaction expiration check result in reward tokens selling at a lower price

## Summary
Selling of reward tokens misses the transaction expiration check, which may lead to tokens being sold at a price that's lower than the market price at the moment of a swap.
## Vulnerability Detail
In the rebalanceAll function, a swap is performed. However, this function does not allow specifying a deadline.

Transaction expiration check allows users to protect from selling tokens at an outdated price that's lower than the current price. Consider this scenario:
1. The `rebalanceAll` function is called on the Ethereum mainnet.

2. Before the transaction is mined, there's a rapid increase of gas cost. The transaction remains in the mempool for some time since the gas cost paid by the transaction is lower than the current gas price.

3. While the transaction is in the mempool, the price of the token1 increases.

4. After a while, gas cost drops and the transaction is mined.  As a result tokens are swapped at an outdated price
## Impact
MultiPool may receive less tokens than expected
## Code Snippet
https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Multipool.sol#L845

https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Multipool.sol#L44-L53
## Tool used

Manual Review

## Recommendation
Implement deadline parameter in rebalanceAll function. For example, [Uniswap sets it to 30 minutes on the Etehreum mainnet and to 5 minutes on L2 networks](https://github.com/Uniswap/interface/blob/main/src/constants/misc.ts#L7-L8).

Duplicate of #163

**Comment by fann95** [comment]
Our team does not consider such a check necessary and allows for a delay in deposit and withdrawals subject to the conditions of slippage protection.The deadline check will be included in swapData if needed
