### ISSUE TITLE
duc - The attacker can repeatedly deposit and withdraw in order to claim the funds of the Multipool contract

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-real-wagmi-judging#121]
duc

high

# The attacker can repeatedly deposit and withdraw in order to claim the funds of the Multipool contract

## Summary
When withdrawing, users will receive a portion of token amounts from the Multipool contract based on their LP amounts. This situation allows the attacker to claim all the funds within the Multipool contract by repeatedly depositing and withdrawing from it.
## Vulnerability Detail
In `withdraw` function:
```solidity=
withdrawnAmount0 +=
    ((IERC20(token0).balanceOf(address(this)) - withdrawnAmount0) * lpAmount) /
    _totalSupply;
withdrawnAmount1 +=
    ((IERC20(token1).balanceOf(address(this)) - withdrawnAmount1) * lpAmount) /
    _totalSupply;

ErrLib.requirement(
    withdrawnAmount0 >= amount0OutMin && withdrawnAmount1 >= amount1OutMin,
    ErrLib.ErrorCode.PRICE_SLIPPAGE_CHECK
);

_burn(msg.sender, lpAmount);
_pay(token0, address(this), msg.sender, withdrawnAmount0);
_pay(token1, address(this), msg.sender, withdrawnAmount1);
```
Users will receive a portion of the funds in the Multipool contract, even if these funds were collected before and the user has not made any contributions. It allows attacker to repeatedly deposit and withdraw in order to claim all the funds within the Multipool contract.

Scenario:
1. Currently, there are 10,000 USDC and 10,000 USDT in the Multipool contract, collected from UniSwapV3 fees. The total supply of the Multipool is 1e18.
2. The attacker utilizes a flashloan to deposit a significant amount into the Multipool contract, obtaining 1e18 LP amounts, and withdraws these LP tokens from the Multipool in the same transaction to repay the flashloan. Consequently, the total supply increases to 2e18.
3. During the withdrawal process, the attacker will claim 5000 USDC and 5000 USDT since their LP amounts represent half of the total supply.
4. The attacker repeats steps 2 and 3, claiming an additional 2500 USDC.
5. The attacker continues until they have claimed most of the funds within the Multipool contract.
## Impact
Loss of funds in Multipool contract
## Code Snippet
https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Multipool.sol#L567-L581
## Tool used
Manual review

## Recommendation
Should use a new mechanism to accumulate the fees of each user (using mapping for accumulating) instead of transferring a portion of contract balance when withdrawing.

**Comment by huuducsc** [comment]
Escalate
This issue is not a duplicate of #158. It presents a clear scenario in which an attacker can steal the funds of the Multipool contract without any distribution. Therefore, I believe it is a valid high.

**Comment by sherlock-admin** [comment]
> Escalate
> This issue is not a duplicate of #158. It presents a clear scenario in which an attacker can steal the funds of the Multipool contract without any distribution. Therefore, I believe it is a valid high.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Sponsor comment:
> this is not a realistic scenario since the number of LPs is calculated taking into account the accumulated commissions in the multipool

**Comment by hrishibhat** [comment]
@huuducsc

**Comment by huuducsc** [comment]
> https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Multipool.sol#L567-L581

I agree and acknowledge that this issue should be considered invalid.

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
While this is not a duplicate of #158 Considering this issue a non-issue based on the above comments

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [huuducsc](https://github.com/sherlock-audit/2023-06-real-wagmi-judging/issues/121/#issuecomment-1632758266): accepted
