### ISSUE TITLE
crimson-rat-reach - Fees accumulated while Multipool tokens are not staked in Dispatcher end up lost

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-real-wagmi-judging#128]
crimson-rat-reach

high

# Fees accumulated while Multipool tokens are not staked in Dispatcher end up lost

## Summary
Fees accumulated while Multipool tokens are not staked in Dispatcher end up lost

## Vulnerability Detail
Fee growth for tokens deposited in Multipool are tracked for the whole Multipool in vars:
https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Multipool.sol#L93

However a user (Alice) cannot withdraw her fees if she keeps her Multipool tokens outside of `Dispatcher`. 
When she decides to deposit her Multipool tokens in the dispatcher, her fee index gets tracked, allowing her to claim fees from multipool from that point on:
https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Dispatcher.sol#L203-L204

But if Alice waits too long before depositing tokens into the Dispatcher, the fees accumulated for her tokens end up lost, and may further break accounting for the `Dispatcher`, as lp tokens withdrawed to service fees are computed using `_totalSupply` for the MultiPool:
https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Dispatcher.sol#L196 

Which means that those fees are not even distributed accross earlier Dispatcher depositors, and are simply lost.

## Impact
Part of Uniswap liquidity gathered fees end up lost for Multipool tokens not deposited into Dispatcher straight away. 

## Tool used

Manual Review

## Recommendation
This mechanism needs rethinking, either keeping track of fees accumulated for a user directly in Multipool in the same manner as it is done currently in `Dispatcher`, or an easier solution is to create a periphery which deposits in `Multipool` and restakes in `Dispatcher` in the same transaction

**Comment by eliteWalrus4164** [comment]
Escalate

Should be a duplicate of #6, fees are only claimable through dispatcher. At the moment feeDebt is set on dispatcher (as it is during deposit), fees before that are lost.

**Comment by sherlock-admin** [comment]
> Escalate
> 
> Should be a duplicate of #6, fees are only claimable through dispatcher. At the moment feeDebt is set on dispatcher (as it is during deposit), fees before that are lost. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by fann95** [comment]
This issue is invalid since the accumulated fees are part of the LP token and do not depend on whether you will deposit to the dispatcher. The depositing to the dispatcher only allows you to track and withdraw the accumulated fees from the LP token by burning part of this LP token.

**Comment by eliteWalrus4164** [comment]
Agreed with sponsor

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Considering this a non-issue based on the above comments

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [crimson-rat-reach](https://github.com/sherlock-audit/2023-06-real-wagmi-judging/issues/128/#issuecomment-1634702412): rejected
