### ISSUE TITLE
mau - Duplicate fee addition in _addUnderlyingPool function

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-real-wagmi-judging#147]
mau

medium

# Duplicate fee addition in _addUnderlyingPool function

## Summary
The `_addUnderlyingPool` function is responsible for adding a new pool to the `underlyingTrustedPools` mapping. However, it lacks checks to prevent the addition of duplicate fees in the `fees` array. This issue can have adverse effects on future functions that rely on this array, especially if they involve looping through the `fees`.

## Vulnerability Detail

In the current implementation, when a new pool is added to the `underlyingTrustedPools` mapping, the corresponding `fee` is appended to the `fees` array without checking for duplicates. Consequently, if the same `fee` value is added multiple times, it will appear multiple times in the array.

## Impact

If future functions utilize the `fees` array and loop through its elements, the presence of duplicate `fees` can lead to inefficiencies. For each duplicate `fee`, the function will perform redundant operations, impacting the overall performance and potentially leading to unexpected behavior.

## Code Snippet

https://github.com/sherlock-audit/2023-06-real-wagmi/blob/82a234a5c2c1fc1921c63265a9349b71d84675c4/concentrator/contracts/Multipool.sol#L171

## Tool used

Manual Review

## Recommendation

Modify the `_addUnderlyingPool` function to include a check before appending the `fee` to the `fees` array. This check will ensure that the `fee` being added does not already exist in the array, preventing duplicates.

**Comment by fann95** [comment]
fixed:https://github.com/RealWagmi/concentrator/blob/9036fe43b0de2694a0c5e18cfe821d40ce17a9b8/contracts/Multipool.sol#L176

**Comment by 0xffff11** [comment]
Fixed by adding a check that the fee already does not exist before pushing the fee to the array
