### ISSUE TITLE
Avci - The estimated remove amount for lp token amount to remove after withdraw is based on total supply can be manipulated and its possible to even withdraw more than share

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-real-wagmi-judging#172]
Avci

high

# The estimated remove amount for lp token amount to remove after withdraw is based on total supply can be manipulated and its possible to even withdraw more than share

## Summary
The estimated remove amount for the lp token amount to remove after withdrawal is based on the total supply can be manipulated and it's possible to even withdraw more than the share
## Vulnerability Detail
when the logic of the   function   _estimateWithdrawalLp : depends on total supply then its possible to manipulate the _estimateWithdrawalLp  return which calculates the 
```solidity
 shareAmount =
            ((amount0 * _totalSupply) / reserve0 + (amount1 * _totalSupply) / reserve1) /
            2;
```
and because this function is called in other functions 
```solidity 
 function estimateClaim(
        uint256 pid,
        address userAddress
    )
        external
        view
        checkPid(pid)
        returns (uint256 lpAmountRemoved, uint256 amount0, uint256 amount1)
    {
        PoolInfo memory pool = poolInfo[pid];
        UserInfo memory user = userInfo[pid][userAddress];
        if (user.shares > 0) {
            IMultipool.FeeGrowth memory feesGrow = IMultipool(pool.multipool)
                .feesGrowthInsideLastX128();
            (uint256 fee0, uint256 fee1) = _calcFees(feesGrow, user);
            (
                uint256 reserve0,
                uint256 reserve1,
                uint256 pendingFee0,
                uint256 pendingFee1
            ) = IMultipool(pool.multipool).getReserves();
            uint256 _totalSupply = IERC20(pool.multipool).totalSupply();
            fee0 += (pendingFee0 * user.shares) / _totalSupply;
            fee1 += (pendingFee1 * user.shares) / _totalSupply;
            lpAmountRemoved = _estimateWithdrawalLp(reserve0, reserve1, _totalSupply, fee0, fee1);
            amount0 = (reserve0 * lpAmountRemoved) / _totalSupply;
            amount1 = (reserve1 * lpAmountRemoved) / _totalSupply;
        }
    }
```
bad actors cam manipulate lpAmountRemoved  easily 
## Impact
 its possible to even withdraw more than share/ create unwanted results 
## Code Snippet
```solidity

    function _estimateWithdrawalLp(
        uint256 reserve0,
        uint256 reserve1,
        uint256 _totalSupply,
        uint256 amount0,
        uint256 amount1
    ) private pure returns (uint256 shareAmount) {
        shareAmount =
            ((amount0 * _totalSupply) / reserve0 + (amount1 * _totalSupply) / reserve1) /
            2;
    }
```
https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Dispatcher.sol#L139-L150
## Tool used

Manual Review

## Recommendation
- consider redesigning the logic to a way that logic does not rely on supply in the way that it can get manipulated

**Comment by huuducsc** [comment]
Escalate

I believe this issue is not a duplicate of #142. Issue #142 describes the significant loss when withdrawing due to changes in the reserves. However, this issue describes the changes in the total supply, which I believe is invalid because manipulating the `totalSupply` does not provide any advantage for the attacker.
Here is my reason why this issue is invalid.
1. If an attacker withdraws their LP shares in Multipool contracts to decrease the `totalSupply`, it is not a problem because these are their owned LP shares. They can't withdraw more than their LP shares
2. If an attacker executes a flashloan to deposit into Multipool contracts and increase the `totalSupply`, they need to withdraw more LP shares from the Dispatcher contract to obtain the same token amounts. This is because the increase in `totalSupply` results in an increase in `_estimateWithdrawalLp`. Therefore, the attacker will be at a disadvantage.

**Comment by sherlock-admin** [comment]
> Escalate
> 
> I believe this issue is not a duplicate of #142. Issue #142 describes the significant loss when withdrawing due to changes in the reserves. However, this issue describes the changes in the total supply, which I believe is invalid because manipulating the `totalSupply` does not provide any advantage for the attacker.
> Here is my reason why this issue is invalid.
> 1. If an attacker withdraws their LP shares in Multipool contracts to decrease the `totalSupply`, it is not a problem because these are their owned LP shares. They can't withdraw more than their LP shares
> 2. If an attacker executes a flashloan to deposit into Multipool contracts and increase the `totalSupply`, they need to withdraw more LP shares from the Dispatcher contract to obtain the same token amounts. This is because the increase in `totalSupply` results in an increase in `_estimateWithdrawalLp`. Therefore, the attacker will be at a disadvantage.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by 0xarshia** [comment]
i think the issue is valid as also #160 pointed that issue and even if we want to separate these we can put this issue with #160 to have a more precise categories

**Comment by hrishibhat** [comment]
@ctf-sec @0xffff11 
Let me know what you think if this?
https://github.com/sherlock-audit/2023-06-real-wagmi-judging/issues/172#issuecomment-1632941344

**Comment by ctf-sec** [comment]
Althought this report does not provide as much detail as possible, I still see this issue as duplicate of #160 

In 160

> However, it is important to note that the values of reserve0 and reserve1 can fluctuate significantly. This is because the positions of the Multipool in UniSwapV3 pools (concentrated) are unstable on-chain, and they can change substantially as the state of the pools changes. As a result, the _estimateWithdrawalLp function might return a large value even for a small fee amount. This could potentially lead to reverting due to underflow in the deposit function (in cases where lpAmount > user.shares), or it could result in withdrawing a larger amount of Multipool LP than initially expected.

In this report

> its possible to even withdraw more than share/ create unwanted results

the wording "create unwanted results" is too vague

but "its possible to even withdraw more than share" partially identify the impact

**Comment by hrishibhat** [comment]
@0xarshia 
If you think this is valid can you respond to these comments?
https://github.com/sherlock-audit/2023-06-real-wagmi-judging/issues/172#issuecomment-1632941344

**Comment by 0xarshia** [comment]
Hey @hrishibhat I believe this issue is valid and yeah i agree it maybe not duplicate of 142 
Calculating shares with totalSupply can be manipulatable, if user deposit token and transfer tokens directly can manipulate share per token.

but my issue is valid as ctf-sec agrees with it. So in this position We can make this solo valid I believe.

Thanks 🙏🏻

**Comment by hrishibhat** [comment]
@0xarshia Can you please share how manipulating `totalSupply` is beneficial for the attacker. 
To be specific can you respond to these comments from the escalation? 
> Here is my reason why this issue is invalid.

> 1.If an attacker withdraws their LP shares in Multipool contracts to decrease the totalSupply, it is not a problem because these are their owned LP shares. They can't withdraw more than their LP shares
> 2.If an attacker executes a flashloan to deposit into Multipool contracts and increase the totalSupply, they need to withdraw more LP shares from the Dispatcher contract to obtain the same token amounts. This is because the increase in totalSupply results in an increase in _estimateWithdrawalLp. Therefore, the attacker will be at a disadvantage.

**Comment by huuducsc** [comment]
I believe `totalSupply` cannot be manipulated. https://github.com/sherlock-audit/2023-06-real-wagmi-judging/issues/160#issuecomment-1646804963

**Comment by 0xarshia** [comment]
@hrishibhat 
There is several ways that is profitable for the attacker or non-profitable but is grief and damage for users.

For e.g if users wants to withdraw the function calculates the amount of lp 

as 
```solidity 
lpAmount = _estimateWithdrawalLp(reserve0, reserve1, _totalSupply, fee0, fee1);
```

So as you see the estimate withdraw is the value of lp amount and becauSe estimate withdrawal is manipulatable with manipulation of total supply of pool  


The lpamount can be higher than expected 
And users will face revert in this part of code 

```solidity 
user.shares -= lpAmount;
```
Will revert


Thus user would not able to withdraw due to lpamount being higher than shares.

This is one of impacts. And is Valid impact 

Thanks 🙏🏻 @hrishibhat

**Comment by huuducsc** [comment]
@0xarshia `_totalSupply` of `Dispatcher.withdraw()` function is the totalSupply of Multipool contract: https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Dispatcher.sol#L219-L223
```solidity=
(
    uint256 reserve0,
    uint256 reserve1,
    IMultipool.FeeGrowth memory feesGrow,
    uint256 _totalSupply
) = IMultipool(pool.multipool).snapshot();
```
The only way to increase the `_totalSupply` is through the `deposit` function of Multipool contract, which adds more liquidity to Multipool's positions and mints Multipool shares for the sender. This is the normal behavior of the Multipool contract. Thus, `reserve0` and `reserve1` will increase corresponding with `_totalSupply`, so the `_estimateWithdrawalLp` will not change the result. Therefore, the scenario "attacker manipulates totalSupply" is simply impossible.

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Considering this a non issue as the totalSupply cannot be manipulated to cause loss of funds here.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [huuducsc](https://github.com/sherlock-audit/2023-06-real-wagmi-judging/issues/172/#issuecomment-1632941344): accepted
