### ISSUE TITLE
stopthecap - Incorrect order when calling `getAmountOut` calculates incorrectly the amount swapped

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-real-wagmi-judging#47]
stopthecap

medium

# Incorrect order when calling `getAmountOut` calculates incorrectly the amount swapped

## Summary
Incorrect order when calling `getAmountOut` calculates incorrectly the amount swapped

## Vulnerability Detail
When `rebalancingAll()` a certain `amountIn` is sent to be swapped in the aggregator that real wagmi chooses.

```@solidity
 _approveToken(params.zeroForOne ? token0 : token1, params.swapTarget, params.amountIn);
            (bool success, ) = params.swapTarget.call(params.swapData);
```

after the swap, the do check both balances of both tokens to see how much of each token as been sent and got back:

```@solidity
uint reserve0 = IERC20(token0).balanceOf(address(this));
        uint reserve1 = IERC20(token1).balanceOf(address(this));
```

They do make the exact calculation to determine the exact amount swapped: 

```@solidity
 uint256 amountOut = params.zeroForOne
            ? reserve1 - reserve1Before
            : reserve0 - reserve0Before;
```

and for the `amountOut` they check the `getAmountOut()` function that does return the expected amount out that you would get at  that exact time for the `amountIn` sent:   

```@solidity
 uint256 swappedOut = getAmountOut(params.zeroForOne, amountIn);
        if (amountOut < swappedOut) {
            ErrLib.requirement(
                (swappedOut * maxTwapDeviation) / MAX_WEIGHT_UINT256 >= swappedOut - amountOut,
                ErrLib.ErrorCode.PRICE_SLIPPAGE_CHECK
            );
```

The problem is that `getAmountOut` has already been updated after swapping on the wagmi's desired pool, having a divergence in price with the actual `amount` of the swap they did, moving the `reserves` of each token and its `amountsOut`

Therefore the calculation of the `if (amountOut < swappedOut) {` will be wrong, and depending where the reserves and the calculation will move, either the function will fail, or you will accept more slippage, potentially losing tokens, than the intended.

## Impact
Depending where the reserves and the calculation will move, either the function will fail, or you will accept more slippage, potentially losing tokens, than the intended.

## Code Snippet
https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Multipool.sol#L845-L881

https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Multipool.sol#L875
## Tool used

Manual Review

## Recommendation
Move the `getAmountOut` call to before the swap happened, not after

**Comment by huuducsc** [comment]
Escalate

I believe this issue is invalid.
 I think the Watson doesn't understand the aggregator's swap and why the protocol uses an aggregator for swapping but uses a Uniswap pool for slippage check. 
People use aggregators to swap because they result in less slippage compared to swapping directly into a pool or dex (please refer to my explanation of aggregator's swap route https://github.com/sherlock-audit/2023-06-real-wagmi-judging/issues/50#issuecomment-1633187206).
Therefore, the getAmountOut function is used to obtain a "safe" amountOut as a safety check for slippage, not the correct or expected amountOut of the swap. This means that this safety amountOut should be lower than the expected amountOut of the swap.
When the `getAmountOut` function uses a trusted pool with a large volume, as mentioned in the issue #48, it will be safe enough for slippage check in both cases, whether before or after the swap.

**Comment by sherlock-admin** [comment]
> Escalate
> 
> I believe this issue is invalid.
>  I think the Watson doesn't understand the aggregator's swap and why the protocol uses an aggregator for swapping but uses a Uniswap pool for slippage check. 
> People use aggregators to swap because they result in less slippage compared to swapping directly into a pool or dex (please refer to my explanation of aggregator's swap route https://github.com/sherlock-audit/2023-06-real-wagmi-judging/issues/50#issuecomment-1633187206).
> Therefore, the getAmountOut function is used to obtain a "safe" amountOut as a safety check for slippage, not the correct or expected amountOut of the swap. This means that this safety amountOut should be lower than the expected amountOut of the swap.
> When the `getAmountOut` function uses a trusted pool with a large volume, as mentioned in the issue #48, it will be safe enough for slippage check in both cases, whether before or after the swap.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by eliteWalrus4164** [comment]
Escalate

This should be marked as invalid, `getAmountOut` does not use the spot price from UniV3, but a TWAP:
https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Multipool.sol#L823-L826

which is not impacted by operations in the current block (observations are written in a delayed way, references below).
This means the amount returned by `getAmountOut` is not impacted by the swap which happened before.

References to UniswapV3Pool code:

1. Value before the swap is used to write in observations:

https://github.com/Uniswap/v3-core/blob/main/contracts/UniswapV3Pool.sol#L605
https://github.com/Uniswap/v3-core/blob/main/contracts/UniswapV3Pool.sol#L735-L742

2. If value has already been written in current block, it is not updated:


https://github.com/Uniswap/v3-core/blob/main/contracts/libraries/Oracle.sol#L90

**Comment by sherlock-admin** [comment]
> Escalate
> 
> This should be marked as invalid, `getAmountOut` does not use the spot price from UniV3, but a TWAP:
> https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Multipool.sol#L823-L826
> 
> which is not impacted by operations in the current block (observations are written in a delayed way, references below).
> This means the amount returned by `getAmountOut` is not impacted by the swap which happened before.
> 
> References to UniswapV3Pool code:
> 
> 1. Value before the swap is used to write in observations:
> 
> https://github.com/Uniswap/v3-core/blob/main/contracts/UniswapV3Pool.sol#L605
> https://github.com/Uniswap/v3-core/blob/main/contracts/UniswapV3Pool.sol#L735-L742
> 
> 2. If value has already been written in current block, it is not updated:
> 
> 
> https://github.com/Uniswap/v3-core/blob/main/contracts/libraries/Oracle.sol#L90

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
@0xffff11

**Comment by 0xffff11** [comment]
Even though the calculation from the twap will still be wrong because of the incorrect fee tier, that is another separate issue, so for this one specifically I agree with invalid

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Considering this a non issue

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [huuducsc](https://github.com/sherlock-audit/2023-06-real-wagmi-judging/issues/47/#issuecomment-1633208678): accepted
- [crimson-rat-reach](https://github.com/sherlock-audit/2023-06-real-wagmi-judging/issues/47/#issuecomment-1634517982): accepted
