### ISSUE TITLE
stopthecap - Divergence between different DEXs when rebalancing will miss-calculate slippage

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-real-wagmi-judging#50]
stopthecap

high

# Divergence between different DEXs when rebalancing will miss-calculate slippage

## Summary
Divergence between different DEXs when rebalancing will miss-calculate slippage 

## Vulnerability Detail

When rebalancing, real wagmi does use one of their whitelisted contracts (aggregators). As said by the team, 1inch it would be an example of one. 
<img width="289" alt="image" src="https://github.com/sherlock-audit/2023-06-real-wagmi-0xffff11/assets/123578292/4dc72e86-9379-4f8f-8037-3b673466ab0e">
The problem here, is that the actual swapping for rebalancing and the calculation of the `amounOut` is made in different DEXs/aggregators.

- Swapping: 
https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Multipool.sol#L858-L859
- amountOut: 
https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Multipool.sol#L823
 Specially, as deploying in so many chains it will diverge between the DEX pool where you swap and the DEX where you calculate the `amountOut` The `amounOut` in exchange X for `token1` will be be completely different to the `amounOut` in exchange Y for `token1`, because it depends on the reserves in the actual pool.

## Impact
Error on calculating slippage through different DEXs that will cause losing funds due to missing an accurate slippage 

## Code Snippet
https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Multipool.sol#L823
https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Multipool.sol#L858-L859
## Tool used
Manual Review

## Recommendation
Do calculate the slippage from the same DEX where it was swapped

**Comment by huuducsc** [comment]
Escalate 

I believe this issue should be invalid. 
1. I think the Watson doesn't know about what an aggregator is. When the contract calls to aggregators (like 1inch's aggregator) to swap, the swap will pass through multiple pools/dexes, which is called `route`. For example, a route to swap WETH to USDC is `[WETH -> DAI -> USDC, WETH -> USDT -> USDC]` (using 4 pools/dexes in 2 paths: WETH-DAI, DAI-USDC, WETH-USDT, USDT-USDC). You can see that this route doesn't use any WETH-USDC pool/dex. So you can't "Do calculate the slippage from the same DEX" with this swap.
2. The `getAmountOut` function is used to get the "safe" amountOut as a safety check for slippage, not the correct amountOut or the expected amountOut of the swap. This function should use a trusted pool with a large volume, as mentioned in the issue #48,  to ensure sufficient safety. Therefore, the `getAmountOut()` function is safe enough in both cases, whether before or after the swap. Of course, this amountOut should be lower than the expected swap result (as a safety check), so there is no problem.

**Comment by sherlock-admin** [comment]
> Escalate 
> 
> I believe this issue should be invalid. 
> 1. I think the Watson doesn't know about what an aggregator is. When the contract calls to aggregators (like 1inch's aggregator) to swap, the swap will pass through multiple pools/dexes, which is called `route`. For example, a route to swap WETH to USDC is `[WETH -> DAI -> USDC, WETH -> USDT -> USDC]` (using 4 pools/dexes in 2 paths: WETH-DAI, DAI-USDC, WETH-USDT, USDT-USDC). You can see that this route doesn't use any WETH-USDC pool/dex. So you can't "Do calculate the slippage from the same DEX" with this swap.
> 2. The `getAmountOut` function is used to get the "safe" amountOut as a safety check for slippage, not the correct amountOut or the expected amountOut of the swap. This function should use a trusted pool with a large volume, as mentioned in the issue #48,  to ensure sufficient safety. Therefore, the `getAmountOut()` function is safe enough in both cases, whether before or after the swap. Of course, this amountOut should be lower than the expected swap result (as a safety check), so there is no problem.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
@0xffff11

**Comment by fann95** [comment]
using external aggregators is to get the best exchange price, and the getAmountOut function (now getTimeWeightedAmountOut https://github.com/RealWagmi/concentrator/blob/73632d7a962f1e7934da4dc9fa555b786382629e/contracts/Multipool.sol#L843) is used to control slippage. I don't see any problems.

**Comment by 0xffff11** [comment]
I see the point of the watson that escalated the issue but I don't agree. My point here is that as they are deploying in different chains. Some with a very small amount of liquidity, the calculation of the slippage won't be correct. 

First of all 1inch does not even support KAVA (a chain where they will deploy) so I am not sure how they will make the calculation there or if it will straight away revert. 

Uniswap's TWAP (or the equivalent from uni in other chains like zkSync) will return a non-optimal slippage for the swap in the aggregator the way it is done right now. They are always using the 500 fee pool. If the swap was performed in uniswap itself instead of 1inch, the slippage would be more accurate. Highlighting again that 1inch does not support Kava.

**Comment by huuducsc** [comment]
@0xffff11 Using the 500 fee pool is a different issue (#48) that can manipulate the amount of slippage control. 
However, this issue doesn't have anything that attacks the slippage control. The protocol chooses UniswapV3 to calculate the amount of slippage check, and I don't see any problems. As I mentioned before, the swap was performed by an aggregator and will go through multiple pools. You can't get the return amount of this swap by using only 1 pool, so trying to make the slippage "more accurate" doesn't make sense.

**Comment by hrishibhat** [comment]
@0xffff11

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Based on the above discussion, agree with the escalation that there is no impact severe enough to be a medium and the code seems to be working as expected

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [huuducsc](https://github.com/sherlock-audit/2023-06-real-wagmi-judging/issues/50/#issuecomment-1633187206): accepted
