### ISSUE TITLE
stopthecap - Using only 150 blocks as `twapDuration` is very easily to manipulate in low volume pools

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-real-wagmi-judging#51]
stopthecap

high

# Using only 150 blocks as `twapDuration` is very easily to manipulate in low volume pools

## Summary
Using only 150 blocks as `twapDuration` is very easy to manipulate in low volume pools 

## Vulnerability Detail

In the function `getAmountOut` there is hardcoded `150` as the twapDuration. This does mean that 
it returns the cumulative tick and liquidity as of each timestamp secondsAgo from the current block timestamp.

So it returns the TWAP `tickCumulatives` of the last 150 seconds.

Due to real wagmi deploying in a lot to secondary chains like kava and wanting to integrate with a wide variety of pools, the 150 seconds `observe` call is extreamily prone to manipulation. Specially in pools were there are no transactions in 2 minutes (pretty much more than 50% outside ethereum)

Attacker will be able to manipulate the `tickCumulatives` to affect to the amount of slippage expected during rebalances, accepting much more slippage than the contract should, losing funds.

## Impact
Loss of funds due to accepting a much higher amount of slippage because of manipulation

## Code Snippet
https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Multipool.sol#L821-L824
## Tool used

Manual Review

## Recommendation
Increase the TWAP duration to around a (1000)  to get an appropiate and correct exchange rate

**Comment by huuducsc** [comment]
Escalate

I believe this issue should be invalid. The `twapDuration` variable is not hardcoded; it can be set by the setParam function. Please refer to the code snippet provided: https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Multipool.sol#L909-L910.
The protocol team has the ability to modify `twapDuration` for specific chains, so it is not a valid issue.

**Comment by sherlock-admin** [comment]
> Escalate
> 
> I believe this issue should be invalid. The `twapDuration` variable is not hardcoded; it can be set by the setParam function. Please refer to the code snippet provided: https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Multipool.sol#L909-L910.
> The protocol team has the ability to modify `twapDuration` for specific chains, so it is not a valid issue.
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
Initially I think it is too hard to manipulate the liquidity for 2 minutes and attacker's fund can easily get arbitraged away.

but after see this, recommend leave this as a medium finding

https://twitter.com/immunefi/status/1679269307514011652?s=46&t=r79NIHlty5C4Nx5Vig3fdw

![image](https://github.com/sherlock-audit/2023-06-real-wagmi-judging/assets/114844362/be7abdea-e249-41b2-9172-9397f396c115)

**Comment by fann95** [comment]
> The `twapDuration` variable is not hardcoded

I completely agree

**Comment by huuducsc** [comment]
> Initially I think it is too hard to manipulate the liquidity for 2 minutes and attacker's fund can easily get arbitraged away.
> 
> but after see this, recommend leave this as a medium finding
> 
> https://twitter.com/immunefi/status/1679269307514011652?s=46&t=r79NIHlty5C4Nx5Vig3fdw
> 
> ![image](https://user-images.githubusercontent.com/114844362/253365461-be7abdea-e249-41b2-9172-9397f396c115.png)

@ctf-sec I think you still don't understand my escalation. I mentioned that the `twapDuration` variable is not hardcoded and can be changed by the owner/admin, so the values of 150 blocks or 2 minutes are meaningless. In chains where blocks are generated rapidly, the owner/admin can adjust the `twapDuration` of the contract to prevent manipulation. Therefore, this issue should be invalid.

**Comment by ctf-sec** [comment]
> Escalate
> 
> I believe this issue should be invalid. The `twapDuration` variable is not hardcoded; it can be set by the setParam function. Please refer to the code snippet provided: https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Multipool.sol#L909-L910. The protocol team has the ability to modify `twapDuration` for specific chains, so it is not a valid issue.

Agree with this escalation

**Comment by hrishibhat** [comment]
@0xffff11 Seems like a low based on the above comments/escaltion

**Comment by 0xffff11** [comment]
I agree that it can be changed by owner. I also think sponsor did not know the impact of using 150 blocks at the beginning and don't think they would change it neither. Usually this is not set initially. Therefore this would have caused problems when deploying regardless. But it is all subjective to what the sponsor was going to do. Imo it is clear that they did not fully understand it and they were not going to change it for every specific chain, so the setter function to change it would not have really made impact. The only one who knows this is @fann95 though

**Comment by hrishibhat** [comment]
Result:
Low
Has duplicates
Agree with the comment, "chains where blocks are generated rapidly, the owner/admin can adjust the twapDuration of the contract to prevent manipulation."
Additional Sponsor comment
> this parameter will be configured depending on the activity in the pool and the network in which the contracts are deployed

Considering this a low issue

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [huuducsc](https://github.com/sherlock-audit/2023-06-real-wagmi-judging/issues/51/#issuecomment-1633241540): accepted
