### ISSUE TITLE
OxZ00mer - Creating a Multipool with MAKER tokens will always lead to a revert

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-real-wagmi-judging#86]
OxZ00mer

medium

# Creating a Multipool with MAKER tokens will always lead to a revert

## Summary
Multipools with MAKER tokens cannot get created as the transaction will fail upon casting the contract to **`IERC20Metadata`**.

## Vulnerability Detail
Multipools with MAKER tokens cannot get created as the transaction will fail upon casting the contract to **`IERC20Metadata`** because the MAKER token isn't **`IERC20Metadata`** -compatible. Its **`name()`** and **`symbol()`** functions return **`bytes memory`** instead of **`string memory`**, which makes them have different selectors and be incompatible with the standard.

     // @audit the Multipool creation will fail here:
     string memory tokens = string.concat(
        IERC20Metadata(token0).symbol(),
        "/",
        IERC20Metadata(token1).symbol()
     );

## Impact
This effectively makes a very popular token not usable by the protocol.

## Code Snippet
https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Factory.sol#L86-L90

## Tool used

Manual Review

## Recommendation
Consider adding some sort of a try-catch that doesn't revert the transaction upon a fail.
Another thing that may be considered is to do some external calls with the string-returning selector first, and if it fails call it with the bytes selector and then cast the return value into a string.

**Comment by KristianApostolov** [comment]
Escalate
I believe this is a valid medium-severity issue as the contest readme clearly states that every ERC20 token should be supported by the protocol, with the exception of inflationary/deflationary tokens - "USDC,USDT,WBTC,WETH, other wrapped native tokens, and general ERC20 standart with no deflation/inflation model".
https://audits.sherlock.xyz/contests/88

**Comment by sherlock-admin** [comment]
> Escalate
> I believe this is a valid medium-severity issue as the contest readme clearly states that every ERC20 token should be supported by the protocol, with the exception of inflationary/deflationary tokens - "USDC,USDT,WBTC,WETH, other wrapped native tokens, and general ERC20 standart with no deflation/inflation model".
> https://audits.sherlock.xyz/contests/88

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
The MAKER token is not as widely as adopted as USDC or USDT

Recommend adding low severity

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Agree with the Lead judge as this can be considered low. 
There is no loss here, only creating the multipool reverts

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [CrisCodesCrap](https://github.com/sherlock-audit/2023-06-real-wagmi-judging/issues/86/#issuecomment-1632472795): rejected
