### ISSUE TITLE
duc - Reserves calculation of Multipool contract is incorrect

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-real-wagmi-judging#88]
duc

high

# Reserves calculation of Multipool contract is incorrect

## Summary
The `_getReserves` function in the Multipool contract incorrectly accumulates all accrued fees from positions (which have not been collected yet), without deducting the protocol fees. As a result, the returned reserves are higher than the actual value, causing users to receive less LP amounts than they should.
## Vulnerability Detail
In the `_getReserves` function, the protocol fee ratio is used to deduct and accumulate the pending fees (unaccrued fees) from the positions in UniSwapV3 pools.
```solidity=
///https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Multipool.sol#L761-L767
// take away protocol fee
uint256 feeGrowthWeight = MAX_WEIGHT_UINT256 - protocolFeeWeight;
pendingFee0 = (pendingFee0 * feeGrowthWeight) / MAX_WEIGHT_UINT256;
pendingFee1 = (pendingFee1 * feeGrowthWeight) / MAX_WEIGHT_UINT256;

reserve0 += pendingFee0;
reserve1 += pendingFee1;
```
However, the accrued fees (accrued from UniV3 pools but not collected) of the positions are not deducted like that, leading to accumulate reserves incorrectly
```solidity=
///https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Multipool.sol#L710-L720
uint128 tokensOwed0;
uint128 tokensOwed1;
(
    liquidity,
    feeGrowthInside0LastX128,
    feeGrowthInside1LastX128,
    tokensOwed0,
    tokensOwed1
) = IUniswapV3Pool(position.poolAddress).positions(position.positionKey);
reserve0 += tokensOwed0;
reserve1 += tokensOwed1;
```
When depositing or withdrawing, the `_upFeesGrowth` function is triggered, which calculates and transfers the protocol fees to the owner. This results in the actual collected fees of the Multipool contract being less than the calculation performed in the `_getReserve` function.
## Impact
Because the incorrect higher reserve amounts, users will receive less LP amounts than they should.
## Code Snippet
https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Multipool.sol#L710-L720
## Tool used
Manual review

## Recommendation
Should deduct the accrued fees by protocol fee ratio in `_getReserve` function, as the following:
```solidity=
uint256 feeGrowthWeight = MAX_WEIGHT_UINT256 - protocolFeeWeight;
tokensOwed0 = (tokensOwed0 * feeGrowthWeight) / MAX_WEIGHT_UINT256;
tokensOwed1 = (tokensOwed1 * feeGrowthWeight) / MAX_WEIGHT_UINT256;

reserve0 += tokensOwed0;
reserve1 += tokensOwed1;
```

**Comment by huuducsc** [comment]
Escalate

I believe this issue is very different from its duplicates. It doesn't describe the incorrect fee calculation. It describes the incorrect calculation of reserves because the function misses deducting the protocol fee when accumulating the fees to reserves.

> When depositing or withdrawing, the _upFeesGrowth function is triggered, which calculates and transfers the protocol fees to the owner. This results in the actual collected fees of the Multipool contract being less than the calculation performed in the _getReserve function.

**Comment by sherlock-admin** [comment]
> Escalate
> 
> I believe this issue is very different from its duplicates. It doesn't describe the incorrect fee calculation. It describes the incorrect calculation of reserves because the function misses deducting the protocol fee when accumulating the fees to reserves.
> 
> > When depositing or withdrawing, the _upFeesGrowth function is triggered, which calculates and transfers the protocol fees to the owner. This results in the actual collected fees of the Multipool contract being less than the calculation performed in the _getReserve function.
> 
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by juntzhan** [comment]
> Escalate
> 
> I believe this issue is very different from its duplicates. It doesn't describe the incorrect fee calculation. It describes the incorrect calculation of reserves because the function misses deducting the protocol fee when accumulating the fees to reserves.
> 
> > When depositing or withdrawing, the _upFeesGrowth function is triggered, which calculates and transfers the protocol fees to the owner. This results in the actual collected fees of the Multipool contract being less than the calculation performed in the _getReserve function.

Agree, same to #124.

**Comment by fann95** [comment]
reserve0 += tokensOwed0;
reserve1 += tokensOwed1;
these lines of code are more paranoia than a necessity..tokensOwed0 and tokensOwed1 are updated only on deposits and withdrawals, but during the update, they are immediately collected and at that moment the platform fee is taken away. tokensOwed0 and  tokensOwed1 always are zero.

**Comment by fann95** [comment]
I think we will remove these lines of code in the future

**Comment by huuducsc** [comment]
> reserve0 += tokensOwed0; reserve1 += tokensOwed1; these lines of code are more paranoia than a necessity..tokensOwed0 and tokensOwed1 are updated only on deposits and withdrawals, but during the update, they are immediately collected and at that moment the platform fee is taken away. tokensOwed0 and tokensOwed1 always are zero.

I believe `tokensOwed0` and `tokensOwed1` don't always equal to 0. Anyone can mint directly to a position on behalf of its owner in UniswapV3, causing that position to collect the accrued fees. If someone does that, `tokensOwed0` and `tokensOwed1` in the `_getReserves` function (and other functions) will be greater than 0.

**Comment by hrishibhat** [comment]
@fann95

**Comment by hrishibhat** [comment]
@huuducsc 
Additional Sponsor comment:
> "accrued fees are calculated according to the following formula
fee0 += tokensOwed0After - tokensOwed0Before;
fee1 += tokensOwed1After - tokensOwed1Before;
therefore, the volume that is already on the tokensOwed will not be included in the calculation of the commission"

**Comment by huuducsc** [comment]
> @huuducsc Additional Sponsor comment:
> 
> > "accrued fees are calculated according to the following formula
> > fee0 += tokensOwed0After - tokensOwed0Before;
> > fee1 += tokensOwed1After - tokensOwed1Before;
> > therefore, the volume that is already on the tokensOwed will not be included in the calculation of the commission"

I agree with the sponsor that tokensOwedBefore will not be included in `_upFeeGrowth`, so this issue should be a non-issue

**Comment by hrishibhat** [comment]
Result:
Invalid
Has duplicates
Considering this a non-issue based on the above comments

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [huuducsc](https://github.com/sherlock-audit/2023-06-real-wagmi-judging/issues/88/#issuecomment-1633006260): accepted
