### ISSUE TITLE
duc - Users might lose their incentives from Multipool when they deposit to Dispatcher contract

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-real-wagmi-judging#89]
duc

high

# Users might lose their incentives from Multipool when they deposit to Dispatcher contract

## Summary
When depositing or withdrawing from the Dispatcher contract, users will receive their fee rewards from the Multiple pool. However, these fees are reverted to the LP amount based on the current reserves of the Multipool and are withdrawn from the user's shares. This means that users may lose their incentive, as the LP amount they receive might provide more incentives in the future. This is because the collected fees in the Multipool contract will increase over time.
## Vulnerability Detail
`Dispatcher.deposit()` and `Dispatcher.withdraw()` functions collect and transfer the accrued fees of users.
```solidity=
uint256 lpAmount;
{
    (uint256 fee0, uint256 fee1) = _calcFees(feesGrow, user);
    lpAmount = _estimateWithdrawalLp(reserve0, reserve1, _totalSupply, fee0, fee1);

}
user.shares -= lpAmount;
_withdrawFee(pool, lpAmount, reserve0, reserve1, _totalSupply, deviationBP);
```
These fees are converted into LP amounts and withdrawn from the Multipool contract. The corresponding LP amount is deducted from the user's shares, effectively removing it and preventing its claim during withdrawal. However, the LP amount has a higher value than the collected fees due to the Multipool incentives increasing over time as users keep their shares. Consequently, when users withdraw from the Dispatcher contract, they will receive a reduced amount compared to if they had not deposited into the Dispatcher and instead withdrawn directly from the Multipool contract.
## Impact
Users will lose some of their incentives if they deposit into Dispatcher contract.
## Code Snippet
https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Dispatcher.sol#L189-L197
https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Dispatcher.sol#L230-L238
## Tool used
Manual review

## Recommendation
`deposit` and `withdraw` functions in Dispatcher contract shouldn't collect fees by converting to LP amounts.

**Comment by huuducsc** [comment]
Escalate

I believe this issue should be valid. The Dispatcher contract always converts the growth fees of the user into the LP shares of Multipool contract and withdraws them during the `deposit` and `withdraw` functions. This results in the user receiving the funds corresponding to the current growth fees immediately, but they will lose the incentive of holding those LP shares in the future. Additionally, the user's LP shares will be deducted over time, leading to a permanent loss for the user. Therefore, Dispatcher contract shouldn't collect growth fees of user by converting to LP amounts.

**Comment by sherlock-admin** [comment]
> Escalate
> 
> I believe this issue should be valid. The Dispatcher contract always converts the growth fees of the user into the LP shares of Multipool contract and withdraws them during the `deposit` and `withdraw` functions. This results in the user receiving the funds corresponding to the current growth fees immediately, but they will lose the incentive of holding those LP shares in the future. Additionally, the user's LP shares will be deducted over time, leading to a permanent loss for the user. Therefore, Dispatcher contract shouldn't collect growth fees of user by converting to LP amounts.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
The severity seems low, seems like a design choice

> When depositing or withdrawing from the Dispatcher contract, users will receive their fee rewards from the Multiple pool. However, these fees are reverted to the LP amount based on the current reserves of the Multipool and are withdrawn from the user's shares. This means that users may lose their incentive, as the LP amount they receive might provide more incentives in the future. This is because the collected fees in the Multipool contract will increase over time.

**Comment by fann95** [comment]
The user himself decides whether to reinvest the accumulated fees and remain in the LP token or make a deposit to the dispatcher and take the accumulated fee, as they arrive by burning part of the LP token that has risen in price. In any case, it does not lose anything, since the mechanism for burning the LP token is the same as directly or through the dispatcher contract.

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Considering this a non-issue based on the Sponsor comment

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [huuducsc](https://github.com/sherlock-audit/2023-06-real-wagmi-judging/issues/89/#issuecomment-1635604738): rejected
